name: 'Swagger - Github Pages'

on:
  # Runs this workflow every 90 days, so artifacts are alive
  schedule:
    - cron: '* * * 1,4,7,10 *'
  push:
    # TODO: Delete feature/swagger-github-actions branch
    branches: [ master, feature/swagger-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  generate-swagger-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Generate swagger-spec.json
        run: yarn start:swagger-only

      - name: Upload swagger-spec.json
        uses: actions/upload-artifact@v3
        with:
          name: spec-file
          path: swagger-spec.json

  deploy:
    needs: generate-swagger-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download swagger-spec.json
        uses: actions/download-artifact@v3
        with:
          name: spec-file

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger-spec.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui